Fix: properly handle monochrome devices
AaronErhardt/tuxedo-rs pull request #52
Opened 2023-12-26 12:23 UTC by SimonBrandner

2023-12-26 16:56 UTC, SimonBrandner commented
(for anyone interested in getting this running before it is merged: https://github.com/SimonBrandner/dotfiles/commit/f51ec63b3cabc09dd12161e8a925711cdddf4b70)

2023-12-27 16:22 UTC, F3l1XQu1ll commented
Tested on nixos-unstable according to https://github.com/SimonBrandner/dotfiles/commit/f51ec63b3cabc09dd12161e8a925711cdddf4b70 
Controlling the keyboard backlight on my InfinityBook Pro 16 Gen 8 now works like a charm with all three brightness levels using the keyboard shortcut as well as with the controls in GNOME (although the settings in GNOME don't reflect the current state of the backlight, but this seems to be a problem with GNOME)

2023-12-27 21:11 UTC, AaronErhardt requested changes
Looks good except for the left over `println!`.

Also maybe the `match` statements over the `find_map` iterator could be simplified using `unwrap_or_else`.

2023-12-27 21:11 UTC, AaronErhardt commented on tailord/src/main.rs
> +    println!("start_runtime()");
Please remove the `println!`

2023-12-28 16:25 UTC, SimonBrandner commented
> Looks good except for the left over `println!`.

Oops  :sweat_smile: 

> Also maybe the `match` statements over the `find_map` iterator could be simplified using `unwrap_or_else`.

New Rust feature for me - thanks for the pointer - I was hoping there'd be something like this!

2023-12-28 16:42 UTC, AaronErhardt approved these changes
Looks good. Thanks a lot!

2023-12-28 16:42 UTC, merged